packages:
  - packages/*
  - examples
  - docs

catalog:
  '@astrojs/react': ^4.3.0
  '@astrojs/starlight': ^0.35.2
  '@astrojs/starlight-tailwind': ^4.0.1
  '@bufbuild/protobuf': ^2.6.3
  '@changesets/cli': ^2.29.6
  '@fontsource/geist-mono': ^5.2.6
  '@fontsource/geist-sans': ^5.2.5
  '@grpc/grpc-js': ^1.13.4
  '@iconify-json/mdi': ^1.2.3
  '@microsoft/api-extractor': ^7.52.10
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-swc': ^0.4.0
  '@stylexjs/stylex': ^0.15.3
  '@swc/helpers': ^0.5.17
  '@tailwindcss/vite': ^4.1.12
  '@types/google-protobuf': ^3.15.12
  '@types/node': ^24.3.0
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  astro: ^5.13.2
  astro-d2: ^0.8.0
  astro-icon: ^1.1.5
  execa: ^9.6.0
  google-protobuf: ^3.21.4
  grpc-web: ^1.5.0
  protoc-gen-js: ^3.21.4-4
  react: ^19.1.1
  react-dom: ^19.1.1
  rollup: ^4.46.2
  rxjs: ^7.8.2
  sharp: ^0.34.2
  starlight-theme-nova: ^0.9.4
  tailwindcss: ^4.1.12
  ts-proto: ^2.7.7
  typescript: 5.9.2
  vite-plugin-stylex: ^0.13.0
  vitest: ^3.2.4
  winston: ^3.17.0

hoist: false

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - protoc-gen-js
  - sharp
  - '@swc/core'
  - esbuild
  - protobufjs
